// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication11.Data;

namespace WebApplication11.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211108165223_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("WebApplication11.Data.produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estoque = 10,
                            Nome = "Iphone XR",
                            Preco = 2500m
                        },
                        new
                        {
                            Id = 2,
                            Estoque = 5,
                            Nome = "Iphone 13",
                            Preco = 9500m
                        },
                        new
                        {
                            Id = 3,
                            Estoque = 8,
                            Nome = "ASUS Rog Phone 5",
                            Preco = 5500m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
